spring:
  datasource:
    url: jdbc:mysql://47.96.77.27:4399/test?serverTimezone=UTC
    username: root
    password: grant@112358
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: db-pool
      auto-commit: on
      connectionTimeout: 30000
      maxLifetime: 1800000
      idle-timeout: 600000
      data-source-properties:
        characterEncoding: utf-8
        useUnicode: true
        useSSL: true
        allowMultiQueries: true
        autoReconnect: true
        useLegacyDatetimeCode: true
        nullCatalogMeansCurrent: true
        rewriteBatchedStatements: true
      connection-test-query: select 1
      maximum-pool-size: 100
      minimum-idle: 20
